### ISSUE TITLE
`import 'echarts-gl'`导致`ReferenceError: self is not defined`

### ISSUE THREAD

**Issue by 4o4E** [ecomfe/echarts-gl#460]
目的是希望像 https://echarts.apache.org/handbook/zh/how-to/cross-platform/server/ 中描述的那样通过服务端 Canvas 渲染bar3d的图片，但是 `import 'echarts-gl';`会导致错误

我在node中运行如下代码

```js
import * as echarts from 'echarts';
import 'echarts-gl';

console.log("a")
```

控制台出现如下的错误

```log
D:\test>node index.js      
D:\test\node_modules\echarts-gl\dist\echarts-gl.js:10
})(self, function(__WEBPACK_EXTERNAL_MODULE_echarts_lib_echarts__) {
   ^

ReferenceError: self is not defined
    at Object.<anonymous> (D:\test\node_modules\echarts-gl\dist\echarts-gl.js:10:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "node index.js"
  },
  "author": "404E",
  "license": "ISC",
  "dependencies": {
    "echarts": "^5.3.3",
    "echarts-gl": "^2.0.9"
  }
}
```

node版本：`v14.18.1`
nom版本：`6.14.15`

**Comment by lliuYuuan** [comment]
你好,这个问题有解决么?

**Comment by lliuYuuan** [comment]
> > 你好,这个问题有解决么?
> 
> 没有，我放弃了

我找到了.用的是next.js, 在next.config.js 里面用 require("next-transpile-modules")(["echarts"]) 包住.

**Comment by 4o4E** [comment]
> > > > 你好,这个问题有解决么?
> > > 
> > > 
> > > 没有，我放弃了
> > 
> > 
> > 我找到了.用的是next.js, 在next.config.js 里面用 require("next-transpile-modules")(["echarts"]) 包住.
> 
> [hustcc/echarts-for-react#425](https://github.com/hustcc/echarts-for-react/issues/425)

感谢

**Comment by alikleit-ns** [comment]
I have opened an [Issue](https://github.com/apache/echarts/issues/18560) with this Next13. I tried transpiled modules but I can't seem to make the package load. 

can you please take a look?
